class Field:
    chrome_version = "101.0.4951.64"
    webdriver_path = '/driver/chromedriver'
    url = "https://www.saucedemo.com/"
    username_textfield = "//input[@id='user-name']"
    username_password_field = "//input[@id='password']"
    login_button = "//input[@id='login-button']"
    product_label = "//span[@class='title']"
    product_label_text = "Products"
    error_mark = "//*[name()='svg'][@role='img']"
    error_message_container = "//div[@class='error-message-container error']"
    error_message = "//h3[@data-test='error']"
    error_message_text = "Epic sadface: Sorry, this user has been locked out."
    high_to_low = "//option[@value='hilo']"
    add_to_cart = "(//button[@class='btn btn_primary btn_small btn_inventory'])[1]"
    shopping_chart_link = "//a[@class='shopping_cart_link']"
    checkout = "//button[@id='checkout']"
    first_name = "//input[@id='first-name']"
    last_name = "//input[@id='last-name']"
    postal_code = "//input[@id='postal-code']"
    continue_button = "//input[@id='continue']"
    item_total = "//div[@class='summary_subtotal_label'][1]"
    tax = "//div[@class='summary_tax_label']"
    total = "//div[@class='summary_total_label']"
    inventory_item_name = "//div[@class='inventory_item_name']"
    item_cart_quantity = "//div[@class='cart_quantity']"
    inventory_item_price = "//div[@class='inventory_item_price']"
    inventory_images = "//div[@class='inventory_item_img']//img"
